name: Mirror to self-hosted git

on:
  push:
    branches:
      - master  # 选择需要同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to self-hosted Git
        run: |
          git remote add mirror https://git@gitee.com/zhangzhichao/alipay-sdk-php-all.git
          git push mirror --mirror
        env:
          GIT_CREDENTIALS: 526a59013ede7669505310501e64618d
